name: Java Maven with Test Runner

on:
  push:
    branches: [ adam-testing-signin-05-04 ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Install dependencies
        run: mvn install

      - name: Run tests with src/test/java/com/sparta/debugbteam/testframework/TestRunner.java
        run: mvn test -Dtest=src/test/java/com/sparta/debugbteam/testframework/TestRunner.java
